apiVersion: v1
kind: Secret
metadata:
  name: {{ include "contapics-ocr.fullname" . }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.aws.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.aws.secretAccessKey | quote }}
