apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "contapics-minio.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
