apiVersion: v1
kind: Secret
metadata:
  name: {{ include "contapics-minio.fullname" . }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.secrets.minio.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.secrets.minio.rootPassword | quote }}
