apiVersion: v1
kind: Secret
metadata:
  name: {{ include "contapics-backend.fullname" . }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.db.user | quote }}
  DB_PASSWORD: {{ .Values.secrets.db.password | quote }}

  AWS_ACCESS_KEY_ID: {{ .Values.secrets.aws.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.aws.secretAccessKey | quote }}
