apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: contapics-backend
  namespace: default
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      app: contapics-backend-backend
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
